# Generated by Django 4.2.14 on 2024-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caballero_persona',
            name='sexo',
            field=models.BooleanField(),
        ),
    ]
